micronaut:
    application:
        name: secret-santa
endpoints:
    info:
        enabled: true
        sensitive: false

#dataSource:
#    pooled: true
#    url: jdbc:postgresql://192.168.127.157:5432/testing1
#    dbCreate: create-drop
#    username: postgres
#    password:
#    userName: postgres
#    driverClassName: org.postgresql.Driver


postgres:
    reactive:
        client:
            port: 5432
            host: 192.168.127.157
            database: secret-santa
            user: postgres
            password: postgres
            maxSize: 5
